<?php

namespace LaravelApiErrors\Console;

use Illuminate\Console\Command;
use LaravelApiErrors\Support\ErrorCodeRegistry;

class ExportTypescriptCommand extends Command
{
    protected $signature = 'api-errors:ts {--path= : Output file path}';
    protected $description = 'Export all registered API error codes as a TypeScript file.';

    public function handle(ErrorCodeRegistry $registry): int
    {
        $path = $this->option('path') ?? config('api-errors.typescript_path', resource_path('js/api-errors.ts'));

        $codes = $registry->all();

        if (empty($codes)) {
            $this->warn('No error codes registered.');
            return self::FAILURE;
        }

        $lines = [
            '// Auto-generated by laravel-api-errors — do not edit manually.',
            '// Generated at: ' . now()->toIso8601String(),
            '',
            'export const API_ERROR_CODES = {',
        ];

        foreach ($codes as $code => $case) {
            $lines[] = sprintf(
                '  %s: { code: \'%s\', status: %d, domain: \'%s\', message: \'%s\' },',
                $code,
                $code,
                $case->httpStatus(),
                $case->domain(),
                addslashes($case->message()),
            );
        }

        $lines[] = '} as const;';
        $lines[] = '';
        $lines[] = 'export type ApiErrorCode = keyof typeof API_ERROR_CODES;';
        $lines[] = '';

        // Union type
        $lines[] = 'export type ApiErrorResponse = {';
        $lines[] = '  success: false;';
        $lines[] = '  error_code: ApiErrorCode;';
        $lines[] = '  message: string;';
        $lines[] = '  domain: string;';
        $lines[] = '  status: number;';
        $lines[] = '  request_id?: string;';
        $lines[] = '  context?: Record<string, unknown>;';
        $lines[] = '};';
        $lines[] = '';

        // RFC 7807
        $lines[] = 'export type ApiProblemDetail = {';
        $lines[] = '  type: string;';
        $lines[] = '  title: ApiErrorCode;';
        $lines[] = '  status: number;';
        $lines[] = '  detail: string;';
        $lines[] = '  instance: string;';
        $lines[] = '  request_id?: string;';
        $lines[] = '  extensions?: Record<string, unknown>;';
        $lines[] = '};';
        $lines[] = '';

        // Helper
        $lines[] = 'export function isApiError(data: unknown): data is ApiErrorResponse {';
        $lines[] = '  return typeof data === \'object\' && data !== null && \'error_code\' in data && \'success\' in data;';
        $lines[] = '}';
        $lines[] = '';

        $dir = dirname($path);
        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        file_put_contents($path, implode("\n", $lines));

        $this->info("TypeScript error codes exported to: {$path}");
        $this->info(count($codes) . ' error codes exported.');

        return self::SUCCESS;
    }
}
